/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import java.awt.geom.RoundRectangle2D;
/**
 *
 * @author Admin
 */
public class ReservaInfo extends javax.swing.JFrame {

    /**
     * Creates new form UserLogUI
     */
    public ReservaInfo() {
        initComponents();
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0,0,510, 310,20,20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User_logo = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CI = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        FechaEntr = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        FechaSal = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NewUI/Icons/UserIcon.png"))); // NOI18N
        getContentPane().add(User_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 150));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buttons/Back.png"))); // NOI18N
        Back.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.setFocusable(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 170, 70));

        jPanel1.setBackground(new java.awt.Color(32, 32, 33));
        jPanel1.setForeground(new java.awt.Color(32, 32, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CI.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CI.setForeground(new java.awt.Color(255, 255, 255));
        CI.setText("C.I: ");
        jPanel1.add(CI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 270, 40));

        Apellido.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Apellido.setForeground(new java.awt.Color(255, 255, 255));
        Apellido.setText("Apellido");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 130, 40));

        FechaEntr.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        FechaEntr.setForeground(new java.awt.Color(255, 255, 255));
        FechaEntr.setText("Fecha de entrada: ");
        jPanel1.add(FechaEntr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, 40));

        Nombre.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        FechaSal.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        FechaSal.setForeground(new java.awt.Color(255, 255, 255));
        FechaSal.setText("Fecha de salida: ");
        jPanel1.add(FechaSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 280, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 300, 190));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NewUI/Backgrounds/Background.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setNombre(String string){
        Nombre.setText(string);
    }
    public void setApellido(String string){
        Apellido.setText(string);
    }
    public void setCedula(String string){
        CI.setText(string);
    }
    public void setFechaEntr(String string){
        FechaEntr.setText(string);
    }
    public void setFechaSal(String string){
        FechaSal.setText(string);
    }
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        NewClientUI ClientUI= new NewClientUI();
        ClientUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CI;
    private javax.swing.JLabel FechaEntr;
    private javax.swing.JLabel FechaSal;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel User_logo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
